In [74]:
import wooldridge
import pandas as pd

df = wooldridge.data('COUNTYMURDERS')
df.head()

C:\Users\brendan\AppData\Local\Temp/ipykernel_18644/2507511543.py:4: DtypeWarning: Columns (8,9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  df = wooldridge.data('COUNTYMURDERS')

,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,rpcpersinc,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,2,1001,54.05,32216,20.63,15.28,22.33,40.25,167.67,8780.8,29.16,1980,2,0.620810,0.6208095,1,1,0,10.38022,0.0
1,3,1001,53.66,31984,20.19,15.55,22.07,40.36,167.99,8232.8,43.92,1981,1,0.312656,0.937969,1,1,0,10.37299,0.0
2,2,1001,53.75,32036,19.66,15.73,21.80,40.42,166.63,8327.61,71.41,1982,3,0.936446,0.6242977,1,1,0,10.37462,0.0
3,7,1001,53.78,32056,19.10,15.88,21.53,40.47,176.53,8545.55,72.22,1983,7,2.183679,2.183679,1,1,0,10.37524,0.0
4,3,1001,53.91,32128,18.54,15.92,21.26,40.51,166.25,8965.16,40.36,1984,2,0.622510,0.933765,1,1,0,10.37748,0.0

In [75]:
df = df[df['year'] == 1996]

numCountries = len(df['countyid'].unique())
largestMurders = df['murders'].max()

largestExecutions = df['execs'].max()
averageExecs = df['execs'].mean()

zeroExecs = df[df['execs'] == 0]
pctZero = (len(zeroExecs) / len(df))

murderExecCorr = df['murders'].corr(df['execs'])

zeroMurders = len(df[df['murders'] == 0])
averageMurders = df['murders'].mean()

murderExecCorr

0.20950421096745053

In [80]:
df = wooldridge.data('ALCOHOL')
print(df.columns)

numStudents = len(df)

Index(['abuse', 'status', 'unemrate', 'age', 'educ', 'married', 'famsize',
       'white', 'exhealth', 'vghealth', 'goodhealth', 'fairhealth',
       'northeast', 'midwest', 'south', 'centcity', 'outercity', 'qrt1',
       'qrt2', 'qrt3', 'beertax', 'cigtax', 'ethanol', 'mothalc', 'fathalc',
       'livealc', 'inwf', 'employ', 'agesq', 'beertaxsq', 'cigtaxsq',
       'ethanolsq', 'educsq'],
      dtype='object')